USE [master]
GO

/****** Object:  Database [F1_jdmm]    Script Date: 05/03/2023 18:19:23 ******/
CREATE DATABASE [F1_jdmm]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'F1_jdmm', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\F1_jdmm.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'F1_jdmm_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\F1_jdmm_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [F1_jdmm].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [F1_jdmm] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [F1_jdmm] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [F1_jdmm] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [F1_jdmm] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [F1_jdmm] SET ARITHABORT OFF 
GO

ALTER DATABASE [F1_jdmm] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [F1_jdmm] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [F1_jdmm] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [F1_jdmm] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [F1_jdmm] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [F1_jdmm] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [F1_jdmm] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [F1_jdmm] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [F1_jdmm] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [F1_jdmm] SET  ENABLE_BROKER 
GO

ALTER DATABASE [F1_jdmm] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [F1_jdmm] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [F1_jdmm] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [F1_jdmm] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [F1_jdmm] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [F1_jdmm] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [F1_jdmm] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [F1_jdmm] SET RECOVERY FULL 
GO

ALTER DATABASE [F1_jdmm] SET  MULTI_USER 
GO

ALTER DATABASE [F1_jdmm] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [F1_jdmm] SET DB_CHAINING OFF 
GO

ALTER DATABASE [F1_jdmm] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [F1_jdmm] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [F1_jdmm] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [F1_jdmm] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [F1_jdmm] SET QUERY_STORE = OFF
GO

ALTER DATABASE [F1_jdmm] SET  READ_WRITE 
GO


